title:            KuDou's blog
description:      I am a strange man. this is my blog.
url:              # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Kong Kudou # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         Home
    url:          http://ikudou.github.io
    external:     true
  - name:         About
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         Blog
    url:          http://www.kudou.org
  - name:         Email
    url:          mailto:i@kudou.org
    external:     true
  - name:         GitHub
    url:          http://github.com/ikudou/ikudou.github.io
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
