auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: xiaowudesign.github.io
url: http://xiaowudesign.github.io
feed: /atom.xml
author_info: <a href="http://xiaowudesign.github.io/">Xiaowu</a>
